language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

git:
    depth: 1

before_install:
  - python --version

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
  - pip install . --install-option="--no-gui"

script:
  - python3 setup.py build_sphinx
  - pytest
